# -*- coding: utf-8 -*-
"""Tipo de cambio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aG0JjWLK3Y3hA0nE_QivRJdkYUid5i4I
"""

import streamlit as st
import pandas as pd
import requests
from datetime import datetime
import matplotlib.pyplot as plt
import yfinance as yf

# ---------------------------
# CONFIGURACIÓN DE LA PÁGINA
# ---------------------------
st.set_page_config(page_title="Banxico + Dollar Index", layout="wide")

st.title("Gráficos: Tipo de Cambio FIX (Banxico) y Dólar Index (DX-Y.NYB)")

# ---------------------------
# TOKEN DE BANXICO
# ---------------------------
BANXICO_TOKEN = "4f55b130139d44190c5e841c2af22a5fe0ffdbc9496d89d813b84a20f6ca7353"

# ---------------------------
# FUNCIÓN PARA DESCARGAR FIX
# ---------------------------
@st.cache_data
def load_fix_data():
    start_date = "2015-01-01"
    end_date = datetime.now().strftime("%Y-%m-%d")

    url = f"https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos/{start_date}/{end_date}"
    headers = {"Bmx-Token": BANXICO_TOKEN}

    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        return None

    datos = response.json()
    serie = datos["bmx"]["series"][0]["datos"]

    df = pd.DataFrame(serie)
    df["fecha"] = pd.to_datetime(df["fecha"], dayfirst=True)
    df["dato"] = pd.to_numeric(df["dato"], errors="coerce")

    return df


# ---------------------------
# FUNCIÓN PARA DESCARGAR DÓLAR INDEX
# ---------------------------
@st.cache_data
def load_dxy_data():
    ticker = "DX-Y.NYB"
    df = yf.download(ticker, period="2y", interval="1d")
    return df["Close"]


# ---------------------------
# GRÁFICO 1: TIPO DE CAMBIO FIX
# ---------------------------
st.subheader("Tipo de Cambio FIX (Banxico) desde 2015")

df_fix = load_fix_data()

if df_fix is None:
    st.error("No se pudieron obtener datos de Banxico.")
else:
    fig1, ax1 = plt.subplots(figsize=(11, 4))
    ax1.plot(df_fix["fecha"], df_fix["dato"], label="FIX", linewidth=1.8)

    # Punto final
    ax1.scatter(df_fix["fecha"].iloc[-1], df_fix["dato"].iloc[-1], color="red", s=40,
                label=f"Último valor: {df_fix['dato'].iloc[-1]:.2f}")

    ax1.set_title("Tipo de Cambio FIX (MXN/USD)")
    ax1.set_xlabel("Fecha")
    ax1.set_ylabel("Tipo de Cambio")
    ax1.grid()
    ax1.legend()

    st.pyplot(fig1)

# ---------------------------
# GRÁFICO 2: ÍNDICE DEL DÓLAR
# ---------------------------
st.subheader("Índice del Dólar (DX-Y.NYB)")

dxy = load_dxy_data()

if dxy is None or dxy.empty:
    st.error("No se pudieron obtener datos del índice del dólar.")
else:
    fig2, ax2 = plt.subplots(figsize=(11, 4))
    ax2.plot(dxy.index, dxy.values, label="Dollar Index", linewidth=1.8)

    # Punto final
    ax1.scatter(dxy["fecha"].iloc[-1], dxy["dato"].iloc[-1], color="red", s=40,
                label=f"Último valor: {dxy['dato'].iloc[-1]:.2f}")


    ax2.set_title("Índice del Dólar (Últimos 2 años)")
    ax2.set_xlabel("Fecha")
    ax2.set_ylabel("Índice")
    ax2.grid()
    ax2.legend()

    st.pyplot(fig2)

# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color:  #00FF00;
    }
    .css-1d391kg {
        color:  #faf7f8;
    }
</style>
""", unsafe_allow_html=True)
